<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_artist-image',
		'title' => 'artist image',
		'fields' => array (
			array (
				'key' => 'field_58e7d7573821f',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'artist image',
				'required' => 1,
				'save_format' => 'object',
				'preview_size' => 'full',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'artists.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_artist-info',
		'title' => 'artist info',
		'fields' => array (
			array (
				'key' => 'field_58e77014cbb8b',
				'label' => 'Biografie',
				'name' => 'biography',
				'type' => 'wysiwyg',
				'instructions' => 'artist biography',
				'required' => 1,
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_58e810e36e7bf',
				'label' => 'Aufgabenbereich',
				'name' => 'tasks',
				'type' => 'text',
				'instructions' => 'tasks',
				'default_value' => '',
				'placeholder' => 'tasks',
				'prepend' => 'Musszo:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58e810bb6e7bd',
				'label' => 'Genre',
				'name' => 'genre',
				'type' => 'text',
				'instructions' => 'insert genre',
				'default_value' => '',
				'placeholder' => 'genre',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58e810d26e7be',
				'label' => 'Land',
				'name' => 'country',
				'type' => 'text',
				'instructions' => 'country',
				'default_value' => '',
				'placeholder' => 'country',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58e7712564108',
				'label' => 'Besetzung',
				'name' => 'besetzung',
				'type' => 'wysiwyg',
				'instructions' => 'artist besetzung',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_58e7704acbb8c',
				'label' => 'Referenzen',
				'name' => 'refs',
				'type' => 'wysiwyg',
				'instructions' => 'artist referenzen',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_58e77086cbb8d',
				'label' => 'Pressestimmen',
				'name' => 'press',
				'type' => 'wysiwyg',
				'instructions' => 'artist Pressestimmen',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'artists.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_artist-product-overview',
		'title' => 'artist product overview',
		'fields' => array (
			array (
				'key' => 'field_58e7719fd9887',
				'label' => 'product title',
				'name' => 'product_title',
				'type' => 'text',
				'instructions' => 'product title',
				'default_value' => 'product title',
				'placeholder' => 'product title',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58e773464c1bd',
				'label' => 'product image',
				'name' => 'product_image',
				'type' => 'image',
				'instructions' => 'product image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_58e7735f4c1be',
				'label' => 'product type',
				'name' => 'product_type',
				'type' => 'select',
				'instructions' => 'product type',
				'choices' => array (
					'Audio CD' => 'Audio CD',
					'Vinyl' => 'Vinyl',
					'T-Shirt' => 'T-Shirt',
					'Promo' => 'Promo',
				),
				'default_value' => 'Audio CD',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'artists.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_artist-social-media',
		'title' => 'artist social media',
		'fields' => array (
			array (
				'key' => 'field_58e8282e76af6',
				'label' => 'homepage',
				'name' => 'homepage',
				'type' => 'text',
				'instructions' => 'artist homepage',
				'default_value' => '',
				'placeholder' => 'http://www.artistpage.com',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58e8277d38950',
				'label' => 'facebook',
				'name' => 'facebook',
				'type' => 'text',
				'instructions' => 'facebook link',
				'default_value' => '',
				'placeholder' => 'http://www.facebook.com/artistpage',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58e827c238951',
				'label' => 'twitter',
				'name' => 'twitter',
				'type' => 'text',
				'instructions' => 'twitter link',
				'default_value' => '',
				'placeholder' => 'http://www.twitter.com/artistProfile',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'artists.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 3,
	));
}

?>
